export const statsConfig = {
  // Chiffres clés — ajuste les nombres à ta réalité
  stats: [
    { number: "3", plus: true, label: "Années d'exp." },
    { number: "9", plus: true, label: "Projets livrés" },
    { number: "10", plus: true, label: "Clients satisfaits" },
    { number: "8", plus: false, label: "Technologies" },
  ],
  toolsLabel: "Outils de travail",
  // Pastille colorée = couleur emblématique de chaque techno
  tools: [
    { name: "React", color: "#61DAFB" },
    { name: "Next.js", color: "#9CA3AF" },
    { name: "Node.js", color: "#5FA04E" },
    { name: "Rails", color: "#CC0000" },
    { name: "TypeScript", color: "#3178C6" },
    { name: "JavaScript", color: "#F7DF1E" },
    { name: "PHP", color: "#777BB4" },
    { name: "Python", color: "#3776AB" },
    { name: "Flutter", color: "#02569B" },
    { name: "Tailwind CSS", color: "#38BDF8" },
    { name: "MongoDB", color: "#47A248" },
    { name: "Firebase", color: "#FFCA28" },
    { name: "Redis", color: "#DC382D" },
    { name: "Docker", color: "#2496ED" },
    { name: "Git", color: "#F05032" },
    { name: "GitHub Actions", color: "#2088FF" },
    { name: "Codemagic", color: "#F45E3F" },
    { name: "Sentry", color: "#6C5FC7" },
    { name: "Linux / VPS", color: "#FCC624" },
    { name: "Streamlit", color: "#FF4B4B" },
    { name: "Stitch", color: "#4285F4" },
    { name: "Pencil Dev", color: "#F59E0B" },
    { name: "Wishy AI", color: "#EC4899" },
  ],
} as const;
